// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcugvjpmeigrxxrayjwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdWd2anBtZWlncnh4cmF5andtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzQxNzYsImV4cCI6MjA3MTExMDE3Nn0.DIKWoV2wPDDSnpl15nZ1J5X5mO32yqLImsXSWP7D4p0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});